# Generated by Django 3.2 on 2025-10-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5'), (6, 'Nivel 6'), (7, 'Nivel 7'), (8, 'Nivel 8'), (9, 'Nivel 9'), (10, 'Nivel 10'), (11, 'Nivel 11'), (12, 'Nivel 12'), (13, 'Nivel 13'), (14, 'Nivel 14'), (15, 'Nivel 15'), (16, 'Nivel 16'), (17, 'Nivel 17'), (18, 'Nivel 18'), (19, 'Nivel 19'), (20, 'Nivel 20')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
            options={
                'unique_together': {('question', 'label')},
            },
        ),
    ]
