# Generated by Django 3.2 on 2025-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, help_text='Ruta estática, ej.: core/img/p1.png', max_length=255),
        ),
    ]
